### PR TITLE
Added 2017 Senior Bowl watch list as csv

### PR DESCRIPTION
**Pull request by AlexanderEllis**
#20 Added players from http://www.seniorbowl.com/watch-list-profiles.php as CSV file

### CODE REVIEW

**Comment by zo0o0ot** [comment]
Nice.  If possible, could you remove the comma between the first name and last name?

**Comment by AlexanderEllis** [comment]
No problem!  Should be all set now.  Feel free to let me know if there is anything else you would like changed.

**Comment by zo0o0ot** [comment]
:+1:

**Comment by zo0o0ot** [comment]
Resolved #20

**Pull request merged**
